name = "receipt-splitter"
type = "javascript"

kv_namespaces = [
  { binding = "RECEIPTS", id = "6be3f67f8f364bad92cf927c95627859" }
]

account_id = "6e8ca19eaa8c4606f3e4ae3ff816b8fc"

[build]
command = "npm run build"
output_directory = "build"
node_version = "18.18.0"